### ISSUE TITLE
Proxy issue?

### ISSUE THREAD

**Issue by InfamousBurns** [biom3tric/Kotsh#2]
I was wondering why after loading the proxys my app just sits idle?
is the because the proxys are not good enough?

**Comment by biom3tric** [comment]
Try to debug the app by putting  `Console.WriteLine` everywhere (like after HTTP request, to know the response).
You can also set a reverse proxy like Fiddler to know how app requested your website

**Comment by InfamousBurns** [comment]
Ok thank you! 
I have proxies that require username/passwords what is the format? username:password@ip:port ? 
Thank you so much for your help

**Comment by biom3tric** [comment]
No, use the following format `ip:port:user:pass`.
Also, please note that i developped the Proxy class to allow usage of user/pass proxies but i didn't had proxies to test this feature
